import process from 'process';
import esbuild from 'esbuild';
import builtins from 'builtin-modules';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/
`;

const prod = process.argv[2] === 'production';
const dev = process.argv[2] === 'development';

esbuild
    .build({
        banner: {
            js: banner,
        },
        bundle: true,
        entryPoints: ['main.ts'],
        external: [
            'obsidian',
            'electron',
            'codemirror',
            '@codemirror/autocomplete',
            '@codemirror/closebrackets',
            '@codemirror/commands',
            '@codemirror/fold',
            '@codemirror/gutter',
            '@codemirror/history',
            '@codemirror/language',
            '@codemirror/rangeset',
            '@codemirror/rectangular-selection',
            '@codemirror/search',
            '@codemirror/state',
            '@codemirror/stream-parser',
            '@codemirror/text',
            '@codemirror/view',
            ...builtins,
        ],
        format: 'cjs',
        logLevel: 'info',
        minify: prod ? true : false,
        outdir: '.',
        sourcemap: prod ? false : 'inline',
        target: 'es2018',
        treeShaking: true,
        watch: !prod && !dev,
    })
    .catch(() => process.exit(1));
